---
services:
  postgres:
    image: postgres:16
    container_name: rest-postgres
    restart: always
    environment:
      POSTGRES_DB: restdb
      POSTGRES_USER: restuser
      POSTGRES_PASSWORD: restpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  postgres_data:
